openapi: 3.0.0
info:
  title: Jobs API
  contact: {}
  version: '1.0'
servers:
- url: https://jobs-api-06-freecodecamp.vercel.app/api/v1/
  variables: {}
paths:
  /auth/register:
    post:
      tags:
      - auth
      summary: Register
      operationId: Register
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/RegisterRequest'
              - example:
                  name: test_user
                  email: test_user@test.gmail.com
                  password: '123456'
            example:
              name: test_user
              email: test_user@test.gmail.com
              password: '123456'
        required: true
      responses:
        '201':
          description: User created
        '400':
          description: Mongo server error
      deprecated: false
      security: []
  /auth/login:
    post:
      tags:
      - auth
      summary: Login
      operationId: Login
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/LoginRequest'
              - example:
                  email: test_user@test.gmail.com
                  password: '123456'
            example:
              email: test_user@test.gmail.com
              password: '123456'
        required: true
      responses:
        '200':
          description: Login successfully
        '400':
          description: Mongo server error
        '404':
          description: User not found. Wrong email or password
      deprecated: false
      security: []
  /jobs:
    get:
      tags:
      - jobs
      summary: Get all jobs (by user)
      operationId: Getalljobs(byuser)
      parameters: []
      responses:
        '200':
          description: OK
        '400':
          description: Mongo server error
      deprecated: false
      security:
      - bearer: []
    post:
      tags:
      - jobs
      summary: Create job
      operationId: Createjob
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/CreatejobRequest'
              - example:
                  company: google
                  position: front-end developer
                  status: interview
            example:
              company: google
              position: front-end developer
              status: interview
        required: true
      responses:
        '201':
          description: Job created
        '400':
          description: Mongo server error
      deprecated: false
      security:
      - bearer: []
  /jobs/{id}:
    get:
      tags:
      - jobs
      summary: Get a job
      operationId: Getajob
      parameters:
      - name: id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: 64a1819cfceee597d81d01b1
      responses:
        '200':
          description: OK
        '400':
          description: Mongo server error
        '404':
          description: Job not found
      deprecated: false
      security:
      - bearer: []
    patch:
      tags:
      - jobs
      summary: Update job
      operationId: Updatejob
      parameters:
      - name: id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: 64a1809cfceee597d81d01b4
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/UpdatejobRequest'
              - example:
                  status: intern
            example:
              status: intern
        required: true
      responses:
        '200':
          description: OK
        '400':
          description: Mongo server error
        '404':
          description: Job not found
      deprecated: false
      security:
      - bearer: []
    delete:
      tags:
      - jobs
      summary: Delete job
      operationId: Deletejob
      parameters:
      - name: id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: 64a1809cfceee597d81d01b4
      responses:
        '200':
          description: OK
        '400':
          description: Mongo server error
        '404':
          description: Job not found
      deprecated: false
      security:
      - bearer: []
components:
  schemas:
    RegisterRequest:
      title: RegisterRequest
      required:
      - name
      - email
      - password
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
      example:
        name: test_user
        email: test_user@test.gmail.com
        password: '123456'
    LoginRequest:
      title: LoginRequest
      required:
      - email
      - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: test_user@test.gmail.com
        password: '123456'
    CreatejobRequest:
      title: CreatejobRequest
      required:
      - company
      - position
      - status
      type: object
      properties:
        company:
          type: string
        position:
          type: string
        status:
          type: string
      example:
        company: google
        position: front-end developer
        status: interview
    UpdatejobRequest:
      title: UpdatejobRequest
      required:
      - status
      type: object
      properties:
        status:
          type: string
      example:
        status: intern
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
security: []
tags:
- name: auth
- name: jobs
